[package]
name = "ratelimit_tokio"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
regex = "1.10.2"
crypto_secretbox = "0.1.1"
byteorder = "1.5.0"
discortp = "0.5.0"
audiopus = "0.2.0"
tokio-tungstenite = { version = "*", features = ["native-tls"] }
url = "*"
futures-util = "*"
serde_json = "*"