[package]
name = "ratelimit_tokio"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
url = "*"
futures-util = "*"
serde_json = "*"
songbird = { version = "*", features = ["driver"] }
async-trait = "0.1.74"
axum = {version = "0.6.20", features=["ws"]}
