name: Build

on:
  push:

permissions:
  contents: write

jobs:
  Build:
    name: Build - ${{ matrix.release_for }}
    strategy:
      matrix:
        include:
            # linux
          - release_for: Linux-ARM
            os: ubuntu-20.04
            target: aarch64-unknown-linux-gnu
            bin: songbird_node
            name: aarch64-unknown-linux-gnu.zip
            command: both

          - release_for: Linux-i686
            os: ubuntu-20.04
            target: i686-unknown-linux-gnu
            bin: songbird_node
            name: i686-unknown-linux-gnu.zip
            command: both

          - release_for: Linux-x86_64
            os: ubuntu-20.04
            target: x86_64-unknown-linux-gnu
            bin: songbird_node
            name: x86_64-unknown-linux-gnu.zip
            command: both

          # win
          
          - release_for: Windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            bin: songbird_node.exe
            name: x86_64-pc-windows-msvc.zip
            command: both

          - release_for: Windows-i686
            os: windows-latest
            target: i686-pc-windows-msvc
            bin: songbird_node.exe
            name: i686-pc-windows-msvc.zip
            command: both

          # mac

          - release_for: macOS-x86_64
            os: macOS-latest
            target: x86_64-apple-darwin
            bin: songbird_node
            name: x86_64-apple-darwin.zip
            command: both

          - release_for: macOS-ARM
            os: macOS-latest
            target: aarch64-apple-darwin
            bin: songbird_node
            name: aarch64-apple-darwin.zip
            command: both
          

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set outputs
        id: vars
        shell: bash
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Install Rust
        # Or @nightly if you want
        uses: dtolnay/rust-toolchain@stable
        # Arguments to pass in
        with:
          # Make Rust compile to our target (defined in the matrix)
          targets: ${{ matrix.target }}

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --verbose --release --target ${{ matrix.target }}

      - name: Build archive
        shell: bash
        id: barchive
        run: |
          # Replace with the name of your binary
          binary_name="songbird_node"
          mkdir zip_cp
          mkdir artifact
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            mv "target/${{ matrix.target }}/release/$binary_name.exe" zip_cp
          else
            mv "target/${{ matrix.target }}/release/$binary_name" zip_cp
          fi
          mv "config.json" zip_cp
          7z a "artifact/${{ matrix.release_for }}.zip" "zip_cp/*"


          
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Build
          path: artifact/*
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
      - name: Delete Old Release
        uses: dev-drprasad/delete-tag-and-release@v1.0
        with:
          tag_name: ${{ steps.previoustag.outputs.tag }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          delete_release: true



          
      - name: Upload to release
        if: ${{ steps.barchive.conclusion == 'success' }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: artifact/*
          asset_name: ${{ matrix.asset_name }}
          tag: dev-${{ steps.vars.outputs.sha_short }}
          file_glob: true
          prerelease: true
